# ww4.0, @2022
# 

openapi: 3.0.0

# General Data Model Information
info:
  title: ww4zero Project
  description: Data model for the MOFREITA component developped under the ww4.0 project
  version: 0.0.1
  contact:
    name: Digitalização da Carpintaria Portuguesa Mofreita
    url: https://projectww4zero.pt/
  
components:
  schemas: 
    Owner:
      $ref: "https://raw.githubusercontent.com/iaggocapitanio1/ww4TestImage/main/model/yaml/owner.yaml#owner"
    Project:
      $ref: "https://raw.githubusercontent.com/iaggocapitanio1/ww4TestImage/main/model/yaml/project.yaml#project"
    Part:
      $ref: "https://raw.githubusercontent.com/iaggocapitanio1/ww4TestImage/main/model/yaml/part.yaml#part"


paths:
  /ngsi-ld/v1/entities:
    get:
      responses:
        '200':
          description: 'OK'
          content:
            application/ld+json:
              schema:
                type: object